import NavBar from "@/app/NavBar"
import { Container, Theme } from "@radix-ui/themes"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

import QueryClientProvider from "@/app/QueryClientProvider"
import AuthProvider from "@/app/auth/Provider"
import "@radix-ui/themes/styles.css"
import "./globals.css"
import "./theme-config.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor="violet">
              <NavBar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
